version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/sparta
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: home/ubuntu/sparta/deploy.sh
      timeout: 60
      runas: ubuntu